### ISSUE TITLE
burn.jl uses TimeZones.jl but TimeZones.jl may change behaviour

### ISSUE THREAD

**Issue by iamed2** [JuliaCI/GCBenchmarks#4]
There may be some differences between the behaviour of the GC in the example as reported in https://github.com/JuliaLang/julia/issues/40644 and as is now due to a couple of the fields [becoming `isbits`](https://github.com/JuliaTime/TimeZones.jl/pull/354). As ZonedDateTime might also change again in the future as well, it might be worth making a synthetic struct for testing in burn.jl instead of using ZonedDateTime.

**Comment by oscardssmith** [comment]
we could just pin the version, but making the synthetic benchmark is almost as easy.
